#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "driver/gpio.h"

#define DUALKEY_BUTTON_A_GPIO GPIO_NUM_0
#define DUALKEY_BUTTON_B_GPIO GPIO_NUM_17
#define DUALKEY_WS2812_GPIO GPIO_NUM_21
#define DUALKEY_WS2812_POWER_GPIO GPIO_NUM_40

#define DUALKEY_CHAIN_LEFT_RX_GPIO GPIO_NUM_48
#define DUALKEY_CHAIN_LEFT_TX_GPIO GPIO_NUM_47

#endif
