[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

board_build.flash_size = 2MB
board_build.partitions = minimal.csv
board_upload.flash_size = 2MB

lib_deps =
    t-vk/ESP32 BLE Keyboard@^0.3.2
    h2zero/NimBLE-Arduino@^1.4.0
    adafruit/Adafruit NeoPixel@^1.12.0

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSE_NIMBLE
